"""Plain-language things a person types into the composer's search box.

WHY THIS FILE EXISTS
--------------------
Content coverage used to be a judgement call — "does this domain feel
complete?" — and that judgement has a measurable bias: the technical axes
come out exhaustive and the cultural ones come out thin. `location/` had
twenty sections of aerial, coastal, industrial, studio and urban, and zero
places where more than one person is having a good time. `wardrobe/historical`
had a gold lame disco jumpsuit and there was nowhere in the library to wear
it. Every one of those gaps was found by a user typing a word and getting
nothing back.

So that is what this automates. Each probe is an INTENT, not a taxonomy node:
what someone wants a picture of, in the words they would use. A probe that
finds nothing is a gap, reported as evidence instead of discovered in the UI.

RULES FOR EDITING
-----------------
* Every gap a user reports gets appended here, so it can never come back.
* A probe is the word a PERSON uses, not the word the library uses. If
  "nightclub" only works because we renamed a section to nightclub, the probe
  has stopped testing anything — add "dance floor" and "bouncer" too.
* A probe may be satisfied by an item's text, not just a section name. Finding
  a disco inside wardrobe/historical is a good answer; the search reports
  where it matched.
* Deleting a probe to make the suite green is the one thing that defeats the
  purpose. Fill the gap or move the probe to KNOWN_GAPS with a reason.
"""

# Probes that legitimately find nothing, each with a reason it is not content
# we intend to carry. Keep this list SHORT and argued — it is the escape
# hatch, and a long one means the instrument has been turned off.
KNOWN_GAPS = {
    # nothing yet
}

PROBES = {
    "nightlife": [
        "nightclub",
        "disco",
        "dance floor",
        "party",
        "bar",
        "cocktail",
        "casino",
        "rave",
        "concert",
        "festival",
        "karaoke",
        "speakeasy",
        "rooftop party",
        "neon bar",
        "dj booth",
        "backstage",
    ],
    "celebration": [
        "wedding",
        "birthday",
        "new year",
        "carnival",
        "parade",
        "graduation",
        "masquerade",
    ],
    "glamour heritage": [
        "pin-up",
        "centerfold",
        "burlesque",
        "showgirl",
        "cabaret",
        "bombshell",
        "vintage glamour",
        "boudoir",
        "lingerie",
        "silk robe",
        "feather boa",
        "corset",
    ],
    "everyday places": [
        "gym",
        "office",
        "hospital",
        "school",
        "library",
        "church",
        "courtroom",
        "airport",
        "hotel lobby",
        "restaurant",
        "supermarket",
        "bus stop",
        "playground",
        "swimming pool",
        "parking garage",
        "diner",
    ],
    "weather": [
        "rain",
        "snow",
        "fog",
        "storm",
        "sunset",
        "golden hour",
        "blue hour",
        "overcast",
        "heat haze",
        "aurora",
        "wind",
        "puddles",
    ],
    "camera": [
        "bokeh",
        "macro",
        "wide angle",
        "fisheye",
        "tilt shift",
        "long exposure",
        "drone",
        "film grain",
        "polaroid",
        "black and white",
        "telephoto",
        "flash",
    ],
    "vehicles": [
        "supercar",
        "muscle car",
        "jdm",
        "rally",
        "motorcycle",
        "truck",
        "race track",
        "drift",
        "pit lane",
        "garage",
        "junkyard",
        "off road",
        "classic car",
        "hot rod",
    ],
    "fantasy and scifi": [
        "dragon",
        "elf",
        "wizard",
        "cyberpunk",
        "steampunk",
        "mech",
        "spaceship",
        "alien",
        "post apocalyptic",
        "castle",
        "witch",
        "vampire",
        "knight",
    ],
    "art styles": [
        "oil painting",
        "watercolor",
        "anime",
        "comic book",
        "art nouveau",
        "impressionist",
        "pixel art",
        "3d render",
        "charcoal",
        "graffiti",
        "collage",
        "woodcut",
    ],
    "pose and expression": [
        "sitting",
        "standing",
        "walking",
        "running",
        "jumping",
        "lying down",
        "over the shoulder",
        "hands on hips",
        "laughing",
        "crying",
        "angry",
        "thoughtful",
        "dancing",
        "stretching",
    ],
    "wardrobe": [
        "leather jacket",
        "ball gown",
        "business suit",
        "swimwear",
        "uniform",
        "kimono",
        "streetwear",
        "gothic",
        "dungarees",
        "trench coat",
        "sportswear",
        "raincoat",
    ],
    "beauty": [
        "red hair",
        "braids",
        "ponytail",
        "afro",
        "freckles",
        "tattoos",
        "piercings",
        "smoky eye",
        "curls",
        "bald",
        "beard",
        "glasses",
    ],
    "animals": [
        "cat",
        "dog",
        "horse",
        "wolf",
        "eagle",
        "shark",
        "butterfly",
        "owl",
    ],
    "food": [
        "burger",
        "sushi",
        "coffee",
        "cake",
        "ramen",
        "bread",
        "cheese",
        "wine",
    ],
    "architecture": [
        "brutalist",
        "cathedral",
        "skyscraper",
        "ruins",
        "bridge",
        "lighthouse",
        "greenhouse",
        "staircase",
    ],
    "seasons": [
        "christmas",
        "halloween",
        "autumn",
        "blossom",
        "beach",
        "winter",
        "harvest",
    ],
    # ---- second wave -------------------------------------------------------
    # Written after the first wave went green, deliberately aimed at what the
    # first list under-covered: who a person IS rather than where they are,
    # the craft vocabulary of light and framing, and the popular character
    # archetypes people actually generate.
    "occupation": [
        "nurse",
        "chef",
        "mechanic",
        "soldier",
        "pilot",
        "farmer",
        "barista",
        "firefighter",
        "scientist",
        "dancer",
        "musician",
        "welder",
        "fisherman",
        "librarian",
    ],
    "body and identity": [
        "plus size",
        "mature",
        "petite",
        "athletic build",
        "androgynous",
        "scars",
        "vitiligo",
        "grey hair",
        "wrinkles",
        "muscular",
    ],
    "character archetypes": [
        "samurai",
        "ninja",
        "pirate",
        "cowboy",
        "viking",
        "astronaut",
        "detective",
        "spy",
        "monk",
        "assassin",
        "gladiator",
        "sorcerer",
        "mermaid",
        "angel",
        "demon",
        "superhero",
    ],
    "lighting craft": [
        "rim light",
        "backlight",
        "softbox",
        "hard light",
        "candlelight",
        "firelight",
        "moonlight",
        "practical lamp",
        "split lighting",
        "rembrandt",
        "silhouette",
        "god rays",
        "bounce",
        "high key",
        "low key",
    ],
    "composition craft": [
        "symmetry",
        "negative space",
        "leading lines",
        "close-up",
        "wide shot",
        "low angle",
        "dutch angle",
        "reflection",
        "framing",
        "over the shoulder shot",
        "top down",
        "rule of thirds",
    ],
    "colour": [
        "monochrome",
        "pastel",
        "earth tones",
        "jewel tones",
        "sepia",
        "duotone",
        "complementary",
        "muted",
        "high contrast",
        "teal and orange",
    ],
    "materials": [
        "silk",
        "leather",
        "denim",
        "velvet",
        "lace",
        "wool",
        "chrome",
        "rust",
        "marble",
        "glass",
        "concrete",
        "brass",
    ],
    "wild places": [
        "desert",
        "jungle",
        "tundra",
        "volcano",
        "cave",
        "waterfall",
        "canyon",
        "swamp",
        "glacier",
        "savanna",
        "rice terrace",
        "salt flat",
    ],
    "rooms": [
        "attic",
        "basement",
        "workshop",
        "loft",
        "bathroom",
        "bedroom",
        "walk-in wardrobe",
        "home office",
        "conservatory",
        "hallway",
    ],
    "more vehicles": [
        "bus",
        "tram",
        "tractor",
        "helicopter",
        "submarine",
        "tank",
        "bicycle",
        "scooter",
        "sailboat",
        "steam locomotive",
    ],
    "sky": [
        "rainbow",
        "lightning",
        "milky way",
        "eclipse",
        "full moon",
        "starfield",
        "sunbeams",
        "noctilucent",
    ],
    "periods": [
        "1920s",
        "1950s",
        "1980s",
        "victorian",
        "medieval",
        "renaissance",
        "belle epoque",
        "cold war",
    ],
    # ---- third wave --------------------------------------------------------
    # Run to test whether the instrument had converged or was simply testing
    # what it had just been used to build. Props, textures, crops, hair,
    # sport, region — angles neither earlier wave touched.
    "props": [
        "mirror",
        "umbrella",
        "helmet",
        "guitar",
        "camera",
        "flowers",
        "jewellery",
        "mask",
        "sword",
        "book",
        "cigarette",
        "sunglasses",
    ],
    "textures and effects": [
        "smoke",
        "dust",
        "water droplets",
        "sparks",
        "glitter",
        "bubbles",
        "feathers",
        "petals",
        "shattered glass",
        "steam",
        "ripples",
        "frost",
    ],
    "subject crop": [
        "full body",
        "half body",
        "headshot",
        "from behind",
        "profile view",
        "extreme close-up",
        "wide establishing",
        "waist up",
    ],
    "hair": [
        "bob",
        "pixie cut",
        "long waves",
        "updo",
        "dreadlocks",
        "wet hair",
        "windblown",
        "bangs",
        "shaved sides",
        "ombre",
    ],
    "sport": [
        "surfing",
        "skateboarding",
        "boxing ring",
        "climbing",
        "skiing",
        "stadium",
        "swimming",
        "martial arts",
        "horse racing",
        "cricket",
    ],
    "region": [
        "india",
        "morocco",
        "mexico",
        "brazil",
        "nordic",
        "korea",
        "china",
        "west africa",
        "andes",
        "iceland",
    ],
    "popular subjects": [
        "cyborg",
        "android",
        "fairy",
        "goddess",
        "valkyrie",
        "oni",
        "kitsune",
        "gothic lolita",
        "cosplay",
        "robot",
    ],
    "more food": [
        "pizza",
        "tacos",
        "dessert",
        "breakfast",
        "street food",
        "market stall",
        "cocktail glass",
        "roast",
    ],
    # ---- fourth wave: world enumerations -----------------------------------
    # Not written by me from intuition. Each list is a mechanical enumeration
    # of a real-world domain, taken from the outside — the sports that exist,
    # the trades people work, the instruments people play. That is what found
    # trade at 20% and music at 23% while material sat at 95%: the library knew
    # what the world is MADE OF and almost nothing about what people DO in it.
    # _harness/tools/cross_section.py runs these as an authoring loop.
    "world: sport": [
        "football",
        "basketball",
        "baseball",
        "cricket",
        "rugby",
        "tennis",
        "golf",
        "boxing",
        "wrestling",
        "judo",
        "karate",
        "taekwondo",
        "kickboxing",
        "fencing",
        "archery",
        "shooting",
        "swimming",
        "diving",
        "surfing",
        "sailing",
        "rowing",
        "kayaking",
        "skiing",
        "snowboarding",
        "ice skating",
        "ice hockey",
        "curling",
        "bobsleigh",
        "climbing",
        "bouldering",
        "mountaineering",
        "cycling",
        "bmx",
        "skateboarding",
        "motocross",
        "enduro",
        "rally",
        "karting",
        "drag racing",
        "obstacle race",
        "marathon",
        "sprint",
        "gymnastics",
        "ballet",
        "yoga",
        "pilates",
        "weightlifting",
        "crossfit",
        "parkour",
        "horse riding",
        "polo",
        "dressage",
        "badminton",
        "table tennis",
        "volleyball",
        "handball",
        "darts",
        "bowling",
        "billiards",
        "paragliding",
        "skydiving",
        "scuba diving",
    ],
    "world: flora": [
        "bonsai",
        "oak",
        "birch",
        "pine",
        "willow",
        "maple",
        "cherry blossom",
        "olive tree",
        "palm",
        "baobab",
        "redwood",
        "bamboo",
        "cactus",
        "succulent",
        "fern",
        "moss",
        "lichen",
        "ivy",
        "orchid",
        "rose",
        "sunflower",
        "lavender",
        "tulip",
        "lotus",
        "water lily",
        "wisteria",
        "heather",
        "thistle",
        "reed",
        "seaweed",
        "kelp",
        "mushroom",
        "vineyard",
        "orchard",
        "wheat field",
        "rice paddy",
        "tea plantation",
        "cornfield",
        "meadow",
        "hedgerow",
    ],
    "world: landform": [
        "fjord",
        "canyon",
        "mesa",
        "dune",
        "atoll",
        "archipelago",
        "delta",
        "estuary",
        "moor",
        "heath",
        "steppe",
        "taiga",
        "tundra",
        "savanna",
        "rainforest",
        "mangrove",
        "coral reef",
        "geyser",
        "hot spring",
        "crater",
        "caldera",
        "glacier",
        "iceberg",
        "karst",
        "sinkhole",
        "badlands",
        "salt marsh",
        "oasis",
        "plateau",
        "escarpment",
        "waterfall",
        "rapids",
        "gorge",
        "cave",
    ],
    "world: trade": [
        "blacksmith",
        "carpenter",
        "potter",
        "weaver",
        "glassblower",
        "cobbler",
        "tailor",
        "baker",
        "butcher",
        "florist",
        "watchmaker",
        "luthier",
        "cooper",
        "stonemason",
        "roofer",
        "plumber",
        "electrician",
        "mechanic",
        "welder",
        "farrier",
        "beekeeper",
        "shepherd",
        "vintner",
        "fisherman",
        "logger",
        "miner",
        "surveyor",
        "gardener",
        "chef",
        "barber",
        "tattoo artist",
        "printer",
        "bookbinder",
        "jeweller",
        "upholsterer",
    ],
    "world: instrument": [
        "piano",
        "violin",
        "cello",
        "double bass",
        "guitar",
        "bass guitar",
        "banjo",
        "harp",
        "flute",
        "clarinet",
        "oboe",
        "saxophone",
        "trumpet",
        "trombone",
        "french horn",
        "tuba",
        "drums",
        "timpani",
        "marimba",
        "accordion",
        "bagpipes",
        "sitar",
        "koto",
        "shamisen",
        "erhu",
        "djembe",
        "synthesizer",
        "turntables",
        "organ",
        "harmonica",
    ],
    "world: architecture": [
        "gothic",
        "romanesque",
        "baroque",
        "rococo",
        "neoclassical",
        "art nouveau",
        "art deco",
        "bauhaus",
        "brutalist",
        "modernist",
        "postmodern",
        "deconstructivist",
        "vernacular",
        "adobe",
        "timber frame",
        "stave church",
        "pagoda",
        "stupa",
        "minaret",
        "ziggurat",
        "amphitheatre",
        "aqueduct",
        "lighthouse",
        "windmill",
        "silo",
        "grain elevator",
        "hangar",
        "shipyard",
        "refinery",
        "cooling tower",
    ],
    "world: cuisine": [
        "italian",
        "french",
        "spanish",
        "greek",
        "turkish",
        "lebanese",
        "moroccan",
        "ethiopian",
        "nigerian",
        "indian",
        "thai",
        "vietnamese",
        "korean",
        "japanese",
        "chinese",
        "mexican",
        "peruvian",
        "brazilian",
        "argentinian",
        "caribbean",
        "cajun",
        "nordic",
        "german",
        "polish",
        "georgian",
        "persian",
    ],
    "world: material": [
        "oak",
        "walnut",
        "teak",
        "bamboo",
        "rattan",
        "cork",
        "leather",
        "suede",
        "linen",
        "cotton",
        "silk",
        "wool",
        "cashmere",
        "tweed",
        "denim",
        "canvas",
        "velvet",
        "satin",
        "lace",
        "chiffon",
        "latex",
        "vinyl",
        "neoprene",
        "carbon fibre",
        "titanium",
        "brass",
        "copper",
        "bronze",
        "pewter",
        "chrome",
        "cast iron",
        "concrete",
        "terrazzo",
        "marble",
        "granite",
        "slate",
        "onyx",
        "porcelain",
        "stoneware",
        "blown glass",
        "resin",
        "mother of pearl",
    ],
    "world: period": [
        "prehistoric",
        "bronze age",
        "iron age",
        "ancient egypt",
        "ancient greece",
        "roman empire",
        "byzantine",
        "viking age",
        "medieval",
        "renaissance",
        "elizabethan",
        "baroque era",
        "georgian",
        "regency",
        "victorian",
        "edwardian",
        "belle epoque",
        "roaring twenties",
        "great depression",
        "wartime",
        "atomic age",
        "space age",
        "cold war",
        "disco era",
        "grunge nineties",
        "y2k",
        "post apocalypse",
    ],
    "world: animal": [
        "wolf",
        "fox",
        "bear",
        "lynx",
        "otter",
        "badger",
        "deer",
        "elk",
        "bison",
        "horse",
        "donkey",
        "camel",
        "llama",
        "goat",
        "sheep",
        "pig",
        "cow",
        "eagle",
        "owl",
        "raven",
        "heron",
        "swan",
        "flamingo",
        "peacock",
        "parrot",
        "hummingbird",
        "penguin",
        "seal",
        "whale",
        "dolphin",
        "shark",
        "octopus",
        "jellyfish",
        "seahorse",
        "turtle",
        "crocodile",
        "snake",
        "lizard",
        "frog",
        "butterfly",
        "dragonfly",
        "beetle",
        "bee",
        "spider",
        "cat",
        "dog",
        "rabbit",
        "hedgehog",
        "squirrel",
        "elephant",
        "lion",
        "tiger",
        "giraffe",
        "zebra",
    ],
    "world: craft": [
        "pottery",
        "weaving",
        "knitting",
        "embroidery",
        "quilting",
        "macrame",
        "origami",
        "quilling",
        "calligraphy",
        "bookbinding",
        "marquetry",
        "inlay",
        "enamel",
        "kintsugi",
        "lacquer",
        "batik",
        "tie dye",
        "block printing",
        "glass fusing",
        "stained glass",
        "mosaic",
        "wood carving",
        "whittling",
        "leatherwork",
        "metal chasing",
        "filigree",
        "basketry",
        "candlemaking",
    ],
}


def all_probes():
    """Every probe as (group, term), minus the argued exceptions."""
    return [
        (group, term) for group, terms in PROBES.items() for term in terms if term not in KNOWN_GAPS
    ]
